#!/bin/sh
# CatBSD Darwin Component Extraction Script
# Extracts a Darwin component from Apple OSS and prepares it for porting

set -e

# Check arguments
if [ $# -lt 1 ]; then
    echo "Usage: $0 <component-name>"
    echo ""
    echo "Examples:"
    echo "  $0 launchd"
    echo "  $0 libdispatch"
    echo "  $0 CF"
    echo ""
    exit 1
fi

COMPONENT=$1

echo "=== Extracting Darwin Component: $COMPONENT ==="
echo ""

# Load environment
if [ -f .catbsd.env ]; then
    . ./.catbsd.env
else
    CATBSD_ROOT="$(pwd)"
    CATBSD_SRC="$CATBSD_ROOT/src"
fi

APPLE_DIR="$CATBSD_SRC/apple-oss"
DARWIN_COMPAT="$CATBSD_SRC/darwin-compat"
DEST_DIR="$DARWIN_COMPAT/$COMPONENT"

# Check if Apple OSS exists
if [ ! -d "$APPLE_DIR" ]; then
    echo "Error: Apple OSS not found at $APPLE_DIR"
    echo "Run ./scripts/fetch-sources.sh first"
    exit 1
fi

# Find component in Apple OSS
find_component() {
    echo "Searching for $COMPONENT in Apple OSS..."
    
    # Try exact match
    if [ -d "$APPLE_DIR/$COMPONENT" ]; then
        SRC_DIR="$APPLE_DIR/$COMPONENT"
        echo "  ✓ Found: $SRC_DIR"
        return 0
    fi
    
    # Try case-insensitive search
    FOUND=$(find "$APPLE_DIR" -maxdepth 1 -iname "$COMPONENT" -type d 2>/dev/null | head -n1)
    if [ -n "$FOUND" ]; then
        SRC_DIR="$FOUND"
        echo "  ✓ Found: $SRC_DIR"
        return 0
    fi
    
    echo "  ✗ Component not found"
    echo ""
    echo "Available components:"
    ls -1 "$APPLE_DIR" | head -20
    exit 1
}

# Copy component
copy_component() {
    echo ""
    echo "Copying $COMPONENT to darwin-compat/..."
    
    mkdir -p "$DEST_DIR"
    cp -R "$SRC_DIR"/* "$DEST_DIR/" 2>/dev/null || cp -R "$SRC_DIR" "$DARWIN_COMPAT/"
    
    echo "  ✓ Copied to $DEST_DIR"
}

# Analyze dependencies
analyze_dependencies() {
    echo ""
    echo "Analyzing dependencies..."
    
    DEP_FILE="$DEST_DIR/DEPENDENCIES.txt"
    
    # Find includes
    echo "System includes:" > "$DEP_FILE"
    find "$DEST_DIR" -name "*.c" -o -name "*.h" -o -name "*.cpp" 2>/dev/null | \
        xargs grep -h "^#include <" 2>/dev/null | \
        sort -u >> "$DEP_FILE" || true
    
    echo "" >> "$DEP_FILE"
    echo "Mach/Darwin specific:" >> "$DEP_FILE"
    grep -E "(mach/|darwin/|os/|CoreFoundation/|dispatch/)" "$DEP_FILE" | head -20 >> "$DEP_FILE.tmp" || true
    mv "$DEP_FILE.tmp" "$DEP_FILE" 2>/dev/null || true
    
    # Find syscalls
    echo "" >> "$DEP_FILE"
    echo "Syscalls and kernel APIs:" >> "$DEP_FILE"
    find "$DEST_DIR" -name "*.c" 2>/dev/null | \
        xargs grep -h "syscall\|mach_\|xpc_\|IOKit" 2>/dev/null | \
        head -20 >> "$DEP_FILE" || true
    
    echo "  ✓ Dependencies analyzed: $DEP_FILE"
}

# Create Makefile template
create_makefile() {
    echo ""
    echo "Creating Makefile template..."
    
    MAKEFILE="$DEST_DIR/Makefile.bsd"
    
    # Determine if it's a library or program
    if echo "$COMPONENT" | grep -qi "^lib"; then
        TYPE="library"
        TARGET="LIB"
    else
        TYPE="program"
        TARGET="PROG"
    fi
    
    cat > "$MAKEFILE" << EOF
# FreeBSD Makefile for $COMPONENT
# Generated by extract-darwin-component.sh

# Component type: $TYPE
$TARGET=   $COMPONENT

# Source files (update this list)
SRCS=   # TODO: Add source files

# Include paths
CFLAGS+= -I.
CFLAGS+= -I../shims
CFLAGS+= -DFREEBSD_COMPAT

# Warnings
CFLAGS+= -Wall -Wextra

# Dependencies (update as needed)
# LDADD=  -lpthread -lutil
# DPADD=  \${LIBPTHREAD} \${LIBUTIL}

# FreeBSD compatibility shims
LDADD+= -L../shims -ldarwin_compat

.include <bsd.prog.mk>
# Or for libraries: .include <bsd.lib.mk>
EOF

    echo "  ✓ Created: $MAKEFILE"
    echo "    (Edit this file to add source files and dependencies)"
}

# Create porting checklist
create_checklist() {
    echo ""
    echo "Creating porting checklist..."
    
    CHECKLIST="$DEST_DIR/PORTING_CHECKLIST.md"
    
    cat > "$CHECKLIST" << EOF
# Porting Checklist: $COMPONENT

## Extraction
- [x] Extract source from Apple OSS
- [x] Copy to darwin-compat/$COMPONENT
- [x] Analyze dependencies

## Analysis
- [ ] Review source code structure
- [ ] Identify Mach-specific code
- [ ] List required syscalls
- [ ] Document external dependencies
- [ ] Assess porting difficulty

## Compatibility Layer
- [ ] Identify needed shims
- [ ] Create/update mach_port shim
- [ ] Create/update syscall shims
- [ ] Create/update XPC shim (if needed)
- [ ] Test shims independently

## Build System
- [ ] Update Makefile.bsd with source files
- [ ] Add dependency libraries
- [ ] Configure include paths
- [ ] Test compilation
- [ ] Fix build errors

## Porting
- [ ] Apply FreeBSD compatibility patches
- [ ] Replace Mach calls with shims
- [ ] Adapt to FreeBSD APIs
- [ ] Handle missing features
- [ ] Document changes

## Testing
- [ ] Build successfully
- [ ] Create unit tests
- [ ] Test basic functionality
- [ ] Integration tests
- [ ] Performance testing

## Integration
- [ ] Install to staging directory
- [ ] Update system configuration
- [ ] Test in CatBSD environment
- [ ] Document usage

## Documentation
- [ ] Update component analysis
- [ ] Document API changes
- [ ] Create usage examples
- [ ] Add to main documentation

## Status
- Current Status: Extracted
- Difficulty: TBD
- Estimated Effort: TBD
- Blockers: TBD

## Notes
(Add notes here)
EOF

    echo "  ✓ Created: $CHECKLIST"
}

# Create component analysis
create_analysis() {
    echo ""
    echo "Creating component analysis..."
    
    ANALYSIS="$DEST_DIR/ANALYSIS.md"
    
    # Count lines of code
    LOC=$(find "$DEST_DIR" -name "*.c" -o -name "*.h" -o -name "*.cpp" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo "unknown")
    
    cat > "$ANALYSIS" << EOF
# Component Analysis: $COMPONENT

## Overview
- **Purpose**: (TODO: Describe purpose)
- **Source Location**: $SRC_DIR
- **Size**: ~$LOC lines of code
- **Type**: $(if echo "$COMPONENT" | grep -qi "^lib"; then echo "Library"; else echo "Program"; fi)

## Dependencies

### System Libraries
(See DEPENDENCIES.txt for full list)

### Kernel APIs
- Mach ports: (TODO: Check DEPENDENCIES.txt)
- Syscalls: (TODO: Check DEPENDENCIES.txt)
- XPC: (TODO: Check DEPENDENCIES.txt)

### External Dependencies
- pthread: (TODO: Verify)
- Other: (TODO: Add)

## Porting Assessment

### Difficulty
- [ ] Low (minimal dependencies, straightforward port)
- [ ] Medium (some Mach dependencies, manageable)
- [ ] High (significant Darwin-specific code)
- [ ] Very High (deep kernel integration)

### Estimated Effort
- [ ] Days (1-5)
- [ ] Weeks (1-3)
- [ ] Weeks (4+)
- [ ] Months

### Key Challenges
1. (TODO: List main challenges)
2. 
3. 

### Blockers
- (TODO: List any blockers)

## Integration Strategy

### Required Shims
- [ ] Mach port compatibility
- [ ] Syscall translation
- [ ] XPC compatibility
- [ ] Other: (TODO)

### Build System Approach
- Using BSD make with Makefile.bsd
- (TODO: Add specific build notes)

### Testing Plan
1. (TODO: Outline testing approach)
2. 
3. 

## Implementation Notes

### Code Structure
(TODO: Describe code organization)

### Key Files
- (TODO: List important files)

### API Surface
(TODO: Document public APIs)

## References
- Apple OSS: https://opensource.apple.com/source/$COMPONENT/
- Documentation: (TODO: Add links)

---
Generated: $(date)
EOF

    echo "  ✓ Created: $ANALYSIS"
}

# Summary
print_summary() {
    echo ""
    echo "=== Extraction Complete ==="
    echo ""
    echo "Component: $COMPONENT"
    echo "Location: $DEST_DIR"
    echo ""
    echo "Next steps:"
    echo "  1. Review $DEST_DIR/ANALYSIS.md"
    echo "  2. Check $DEST_DIR/DEPENDENCIES.txt"
    echo "  3. Update $DEST_DIR/Makefile.bsd"
    echo "  4. Follow $DEST_DIR/PORTING_CHECKLIST.md"
    echo ""
}

# Main execution
main() {
    find_component
    copy_component
    analyze_dependencies
    create_makefile
    create_checklist
    create_analysis
    print_summary
}

main
